Add functionality & refactor code

diff --git a/updater b/updater
--- a/updater
+++ b/updater
@@ -1,59 +1,143 @@
 #!/bin/bash
 set -e
-cd /usr/share/updater/
 
-VALID_ARGS=$(getopt -o k,s,h,u: --long kernel,sync,help,update: -- "$@")
+JOBS=$(nproc)
+VALID_ARGS=$(getopt -o k,s,u,U,b,B,K,N,m,D,i,h,j: --long kernel,sync,no-initramfs,menuconfig,defconfig,no-GRUB,custom-kernel-building,help,jobs: -- "$@")
+REMAINING_ARGS=""
+UPDATE_ARGS=false
+UPDATE_BORKED=false
+SYNC=false
+BUILD_REST=false
+
+show_help() {
+    echo "Usage:"
+    echo "-u				update @world"
+    echo "-U				update @world and the kernel"
+    echo "-b				update @world with --emptytree"
+    echo "-B				update @world with --emptytree and update the kernel"
+    echo "-j,--jobs			override kernel build job count (Default is $(nproc))"
+    echo "-h,--help			show this help message"
+    echo "-k,--kernel			rebuild the current kernel"
+    echo "-s,--sync			sync portage before updating"
+    echo "-N,--no-GRUB			call bootloader.sh instead of grub-mkconfig"
+    echo "-i,--no-initramfs		do not call dracut after building the kernel"
+    echo "-m,--menuconfig			call make menuconfig before building the kernel"
+    echo "-D,--defconfig			call make defconfig instead of make olddefconfig"
+    echo "-K,--custom-kernel-building	call ckb.sh instead of building the kernel via build_rest"
+}
+
 if [[ $? -ne 0 ]]; then
-	echo "Usage:"
-	echo "-k,--kernel	rebuild current kernel"
-        echo "-u,--update [input]	update, input 'y' for basic invocation, 'A' for all, 'B' if your system is borked"
-        echo "-s,--sync		does 'emaint sync -A' beforehand"
-        echo "-h,--help		this help output"
+    show_help
 	exit 1;
 fi
 
-F_NAME=""
-
 eval set -- "$VALID_ARGS"
+
 while [ : ]; do
-  case "$1" in
-    -k | --kernel)
-        echo "Building kernel ..."
-	./build_kernel.sh
-        shift
-        ;;
-    -s | --sync)
-        echo "Syncing ..."
-        emerge-webrsync && emaint sync -A && emerge --regen -q
-        shift
-        ;;
-    -h | --help)
-        echo "Usage:"
-	    echo "-k,--kernel       	rebuild current kernel"
-        echo "-u,--update [input]	update, input 'y' for basic invocation, 'A' for all, 'B' if your system is borked"
-        echo "-s,--sync		does 'emaint sync -A' beforehand"
-        echo "-h,--help		this help output"
-	exit 0
-	shift
-	;;
-    --)
-	shift;
-	break
-	;;
-    *)
-	echo "Unexpected option: $1"
-	echo "Usage:"
-        echo "-k,--kernel       rebuild current kernel"
-	    echo "-u,--update [input]	update, input 'y' for basic invocation, 'A' for all, 'B' if your system is borked"
-        echo "-s,--sync		does 'emaint sync -A' beforehand"
-        echo "-h,--help		this help output"
-	exit 1
-	;;
+    case "$1" in
+        -u)
+            UPDATE_ARGS=true
+            shift
+            ;;
+        -U)
+            UPDATE_ARGS=true
+            BUILD_REST=true
+            shift
+            ;;
+        -b)
+            UPDATE_BORKED=true
+            shift
+            ;;
+        -B)
+            UPDATE_BORKED=true
+            BUILD_REST=true
+            shift
+            ;;
+        -s | --sync)
+            SYNC=true
+            shift
+            ;;
+        -k | --kernel)
+            BUILD_REST=true
+            shift
+            ;;
+        -K | --custom-kernel-building)
+            if [ -f "./ckb.sh" ]; then
+                REMAINING_ARGS+="-K "
+            else
+                echo "Error: /usr/share/updater/ckb.sh not found!"
+                exit 1
+            fi
+            shift
+            ;;
+        -N | --no-GRUB)
+            if [ -f "./bootloader.sh" ]; then
+                REMAINING_ARGS+="-N "
+            else
+                echo "Error: /usr/share/updater/bootloader.sh not found!"
+                exit 1
+            fi
+            shift
+            ;;
+        -m | --menuconfig)
+            REMAINING_ARGS+="-m "
+            shift
+            ;;
+        -D | --defconfig)
+            REMAINING_ARGS+="-D "
+            shift
+            ;;
+        -i | --no-initramfs)
+            REMAINING_ARGS+="-i "
+            shift
+            ;;
+        -j | --jobs)
+            JOBS=$2
+            REMAINING_ARGS+="-j $JOBS "
+            shift
+            ;;
+        -h | --help)
+            show_help
+            exit 0
+            shift
+            ;;
+        --)
+            shift;
+            break
+            ;;
+        *)
+            echo "Invalid argument: $1"
+            show_help
+            exit 1
+            ;;
     esac
 done
 
-if [[ $F_NAME != "" ]]; then
-	echo "Running $F_NAME ..."
-	. "./$F_NAME"
+pushd /usr/share/updater
+
+if [ "$SYNC" = true ]; then
+    echo "Syncing..."
+    # emerge-webrsync
+    emaint sync -A
+    emerge --regen -q
 fi
-exit 0
+
+if [ "$UPDATE_BORKED" = true ]; then
+    UPDATE_ARGS=false
+    ./update_whilst_borked
+fi
+
+if [ "$UPDATE_ARGS" = true ]; then
+    ./update
+fi
+
+if [ ! -z "$REMAINING_ARGS" ]; then
+    REMAINING_ARGS=true
+fi
+
+if [ "$BUILD_REST" = true ]; then
+    echo "Calling /usr/share/updater/build_rest..."
+    ./build_rest $REMAINING_ARGS
+fi
+
+popd
